<?php
/**
 * Custom tab template
 */
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('catalog')->__('Create Simple Associated Products') ?></h4>
    </div>
    <div class="fieldset fieldset-wide">
        <?php
        $product = Mage::registry('product');
        $write = Mage::getSingleton('core/resource')->getConnection('core_write');
        $table_name = Mage::getSingleton('core/resource')->getTableName('bialsoft_easyvariantscreator_products');
        $query = 'SELECT product_data, removeoldproducts, status, sortorder   FROM  ' . $table_name . ' WHERE product_id=' . $product->getId();
        $rs = $write->fetchAll($query);
        ?>

        <ul class="messages">
            <li class="notice-msg">
                <ul>
                    <li>Remove old products: <select style="width:100px; margin-right:40px;"  class="removeoldproducts" name="removeoldproducts">
                            <option <?php if ($rs[0]['removeoldproducts']) { ?>selected="selected" <?php } ?> value="1">Yes</option>
                            <option <?php if (!$rs[0]['removeoldproducts']) { ?>selected="selected" <?php } ?> value="0">No</option>
                        </select>
                        State: <select style="width:100px;  margin-right:40px;"  class="vcstate" name="vcstate">
                            <option <?php if ($rs[0]['status']) { ?>selected="selected" <?php } ?> value="1">Enabled</option>
                            <option <?php if (isset($rs[0]['status']) && !$rs[0]['status']) { ?>selected="selected" <?php } ?> value="0">Disabled</option>

                        </select>
                        Sort order: <select style="width:100px;  margin-right:40px;"  class="sortorder" name="sortorder">
                            <option <?php if ($rs[0]['sortorder'] == 0) { ?>selected="selected" <?php } ?> value="0">0</option>
                            <option <?php if ($rs[0]['sortorder'] == 1) { ?>selected="selected" <?php } ?> value="1">1</option>
                            <option <?php if ($rs[0]['sortorder'] == 2) { ?>selected="selected" <?php } ?> value="2">2</option>
                            <option <?php if ($rs[0]['sortorder'] == 3) { ?>selected="selected" <?php } ?> value="3">3</option>
                            <option <?php if ($rs[0]['sortorder'] == 4) { ?>selected="selected" <?php } ?> value="4">4</option>
                            <option <?php if ($rs[0]['sortorder'] == 5) { ?>selected="selected" <?php } ?> value="5">5</option>
                            <option <?php if ($rs[0]['sortorder'] == 6) { ?>selected="selected" <?php } ?> value="6">6</option>
                            <option <?php if ($rs[0]['sortorder'] == 7) { ?>selected="selected" <?php } ?> value="7">7</option>
                            <option <?php if ($rs[0]['sortorder'] == 8) { ?>selected="selected" <?php } ?> value="8">8</option>
                            <option <?php if ($rs[0]['sortorder'] == 9) { ?>selected="selected" <?php } ?> value="9">9</option>
                        </select>
                    </li>

                </ul>


            </li>
        </ul>



        <?php
        if ($rs) {

            $params_relation = array();
            $params = explode(";", $rs[0]['product_data']);
            for ($i = 0; $i < count($params); $i++) {
                $params[$i] = explode(":", $params[$i]);
                $params[$i][1] = explode(",", $params[$i][1]);
                if ($params[$i][0])
                    $params_relation[$params[$i][0]] = $params[$i][1];
            }
            ?>




            <ul class="messages">
                <li class="notice-msg">
                    <ul><li>Products creation already schedulated.</li></ul>
                    <ul><li>All changes will ovverride current settings.</li></ul>
                    <ul><li><a href="<?php echo Mage::getUrl('admin_easyvariantscreator/adminhtml_easyvariantscreator/massCreateSimpleProducts', array('product_id' => $product->getId())); ?>">Create variants</a></li></ul>
                </li>
            </ul>

            <?php
        }
        $configurableProduct = Mage::getModel('catalog/product')
                ->setStoreId(Mage_Core_Model_App::ADMIN_STORE_ID)
                ->load($product->getId());


        if ($configurableProduct->isConfigurable()) {

            $post_values = "";
            $isfirst = true;



            $old_used_attrs = array();
            $config = $configurableProduct->getTypeInstance(true);
            foreach ($config->getConfigurableAttributesAsArray($configurableProduct) as $attributes) {
                foreach ($attributes["values"] as $values) {
                    $old_used_attrs[] = $values["value_index"];
                }
            }


            foreach ($configurableProduct->getTypeInstance()->getConfigurableAttributes() as $attribute) {


                if ($isfirst) {
                    $post_values = $attribute->getProductAttribute()->getId();
                    $isfirst = false;
                } else {
                    $post_values.="," . $attribute->getProductAttribute()->getId();
                }


                $attr = Mage::getSingleton('eav/config')->getAttribute('catalog_product', $attribute->getProductAttribute()->getAttributeCode());


                $options = $attr->getSource()->getAllOptions(false);
                ?>
                <ul class="super-attributes">
                    <li class="attribute" style="position: relative;">


                        <div class="attribute-name-container left" rel="<?php echo $attr->getData('attribute_code'); ?>"><?php echo $attr->getData('frontend_label'); ?></div>
                        <div class="values-container right <?php echo $attr->getData('attribute_code'); ?>" style="display:none;">

                            <?php
                            foreach ($options as $option) {
                                ?>

                                <div class="attribute-values-container-main">
                                    <?php if ((in_array($option['value'], $params_relation[$attribute->getProductAttribute()->getId()]) && $rs ) || (!$rs && in_array($option['value'], $old_used_attrs) )) { ?>

                                        <input type="checkbox" class="multi_product_checkbox" name="options_<?php echo $attribute->getProductAttribute()->getId() ?>[]" checked="checked" value="<?php echo $option['value'] ?>" />
                                    <?php } else { ?>
                                        <input type="checkbox" class="multi_product_checkbox" name="options_<?php echo $attribute->getProductAttribute()->getId() ?>[]" value="<?php echo $option['value'] ?>" />

                                    <?php } ?>

                                    <?php echo $option['label'] ?>
                                </div>

                                <?php
                            }
                            ?>

                        </div>
                        <div style="clear:both; display:block;"> </div>
                    </li>
                </ul>
                <?php
            }
            ?>
            <input type="hidden" name="multi_create_parameters" value="<?php echo $post_values ?>"/>
            <input type="hidden" class="is_needed_save" name="is_needed_save" value=""/>

            <?php
        }
        ?>

    </div>
</div>
<script>

    jQuery(".multi_product_checkbox, .removeoldproducts, .vcstate, .sortorder").change(function () {
        jQuery(".is_needed_save").val("true");

    });


    jQuery(".attribute-name-container.left").click(function () {
        var rell = jQuery(this).attr("rel");
        jQuery(".values-container.right." + rell).toggle();
    });

</script>

